version: '3.8'

services:
  my-python-app:
    build:
      context: .
    container_name: MammaMia
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
